services:
  titanic-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
    depends_on:
      - titanic-data
    restart: unless-stopped
    volumes:
      - titanic-data:/data

  titanic-data:
    build:
      context: .
      dockerfile: Dockerfile.${DATA_SOURCE:-csv}
    command: ["sh", "-c", "cp /seed/titanic.${DATA_SOURCE:-csv} /data/titanic.${DATA_SOURCE:-csv}"]
    volumes:
      - titanic-data:/data
    
volumes:
  titanic-data: